### ISSUE TITLE
403 Forbidden result

### ISSUE THREAD

**Issue by conjwamnc** [wiredmartian/dpo-paygate-payweb3#3]
Good dayWiredMartian, I keep getting some 403 forbidden result. Please show me how I can fix this?

**Comment by wiredmartian** [comment]
Hi @conjwamnc 

PayGate PayWeb3 now needs real/non-localhost urls to work. I've pushed an update and added a comment of what you need to change on this file (DPO-Paygate-PayWeb3/Controllers/PayController.cs)

**Comment by aristocharisma** [comment]
Hi Man when i want to test Reponses how do I do that if my return URL is a website

**Comment by wiredmartian** [comment]
> Hi Man when i want to test Reponses how do I do that if my return URL is a website

Please have a look my above comment, I believe it answers the question. Alternatively, you can have a look at the video on this repo's README file, where it redirects to a website
